fronius:
  baseUrl: http://fronius.local
  prefix: fronius
  meterOffsetIn: 1234
  meterOffsetOut: -5432

ecotouch:
  baseUrl: http://ecotouch.local
  prefix: ecotouch
  username: user
  password: pass

nrgkick:
  baseUrl: http://nrgkick.local
  prefix: nrgkick

graphite:
  hostname: graphite.local
  port: 2003
  prefix: metrics.prefix
  protocol: tcp

watertemp:
  produceThreshold:  -2000,
  produceMinTime:    10,
  producingTemp:     55,
  normalTemp:        48,
  tempChangeMinTime: 30,
