name: Auto-Tag

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    types: [ "closed" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  update_tag:
    if: >-
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'renovate_publish')

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Current version
        run: echo "current_version=$(grep version= build/package/Dockerfile | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Bump Version
        uses: jaumann/github-bumpversion-action@2aa01a9da6481d7b35cd5edbf5da74e1ef2ccbd5 # v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.TAGGING_TOKEN }}

      - uses: butlerlogic/action-autotag@7421fe0300091f3ef2134f627baaad42a156de10 # 1.1.4
        env:
          GITHUB_TOKEN: "${{ secrets.TAGGING_TOKEN }}"
        with:
          strategy: regex
          root: "build/package/Dockerfile"
          regex_pattern: "version=(\\d+\\.\\d+\\.\\d+)"
          tag_prefix: "v"
